#lang racket

(require "lib.rkt"
         "structs.rkt"
         "vect.rkt")

(defchipmunk cpBodyGetMass (_fun _cpBody-pointer -> _cpFloat))
(defchipmunk cpBodyGetMoment (_fun _cpBody-pointer -> _cpFloat))
(defchipmunk cpBodyGetPosition (_fun _cpBody-pointer -> _cpVect))
(defchipmunk cpBodyGetVelocity (_fun _cpBody-pointer -> _cpVect))
(defchipmunk cpBodyGetForce (_fun _cpBody-pointer -> _cpVect))
(defchipmunk cpBodyGetAngle (_fun _cpBody-pointer -> _cpFloat))
(defchipmunk cpBodyGetAngularVelocity (_fun _cpBody-pointer -> _cpFloat))
(defchipmunk cpBodyGetTorque (_fun _cpBody-pointer -> _cpFloat))
(defchipmunk cpBodyGetSpace (_fun _cpBody-pointer -> _cpSpace-pointer))
(defchipmunk cpBodyGetUserData (_fun _cpBody-pointer -> _cpDataPointer))

(defchipmunk cpBodySetMass (_fun _cpBody-pointer _cpFloat -> _void))
(defchipmunk cpBodySetMoment (_fun _cpBody-pointer _cpFloat -> _void))
(defchipmunk cpBodySetPosition (_fun _cpBody-pointer _cpVect -> _void))
(defchipmunk cpBodySetVelocity (_fun _cpBody-pointer _cpVect -> _void))
(defchipmunk cpBodySetForce (_fun _cpBody-pointer _cpVect -> _void))
(defchipmunk cpBodySetAngle (_fun _cpBody-pointer _cpFloat -> _void))
(defchipmunk cpBodySetAngularVelocity (_fun _cpBody-pointer _cpFloat -> _void))
(defchipmunk cpBodySetTorque (_fun _cpBody-pointer _cpFloat -> _void))
(defchipmunk cpBodySetUserData (_fun _cpBody-pointer _cpDataPointer -> _void))

(defchipmunk cpBodyAlloc (_fun -> _cpBody-pointer))
(defchipmunk cpBodyInit (_fun _cpBody-pointer _cpFloat _cpFloat -> _cpBody-pointer))
(defchipmunk cpBodyNew (_fun _cpFloat _cpFloat -> _cpBody-pointer))
(defchipmunk cpBodyNewStatic (_fun -> _cpBody-pointer))
(defchipmunk cpBodyDestroy (_fun _cpBody-pointer -> _cpBody-pointer))
(defchipmunk cpBodyFree (_fun _cpBody-pointer -> _void))
(defchipmunk cpBodyActivate (_fun _cpBody-pointer -> _void))
(defchipmunk cpBodyActivateStatic (_fun _cpBody-pointer _cpShape-pointer -> _void))
(defchipmunk cpBodySleep (_fun _cpBody-pointer -> _void))
(defchipmunk cpBodySleepWithGroup (_fun _cpBody-pointer _cpBody-pointer -> _void))
(defchipmunk cpBodyIsSleeping (_fun _cpBody-pointer -> _cpBool))
(defchipmunk cpBodyUpdateVelocity (_fun _cpBody-pointer _cpVect _cpFloat _cpFloat -> _void))
(defchipmunk cpBodyApplyForceAtWorldPoint (_fun _cpBody-pointer _cpVect _cpVect -> _void))
(defchipmunk cpBodyApplyForceAtLocalPoint (_fun _cpBody-pointer _cpVect _cpVect -> _void))
(defchipmunk cpBodyApplyImpulseAtWorldPoint (_fun _cpBody-pointer _cpVect _cpVect -> _void))
(defchipmunk cpBodyApplyImpulseAtLocalPoint (_fun _cpBody-pointer _cpVect _cpVect -> _void))
(defchipmunk cpBodyGetVelocityAtWorldPoint (_fun _cpBody-pointer _cpVect -> _cpVect))
(defchipmunk cpBodyGetVelocityAtLocalPoint (_fun _cpBody-pointer _cpVect -> _cpVect))
(defchipmunk cpBodyKineticEnergy (_fun _cpBody-pointer -> _cpFloat))
(defchipmunk cpBodyEachShape (_fun _cpBody-pointer _cpBodyShapeIteratorFunc _cpDataPointer -> _void))
(defchipmunk cpBodyEachConstraint (_fun _cpBody-pointer _cpBodyConstraintIteratorFunc _cpDataPointer -> _void))
(defchipmunk cpBodyEachArbiter (_fun _cpBody-pointer _cpBodyArbiterIteratorFunc _cpDataPointer -> _void))